%inverse method

close all; % cleaning
clear all;

number_of_samples = 5000;

x = linspace(0,1,number_of_samples);

seed = 0.712;
random_number_sequence_x = zeros(1,number_of_samples);
random_number_x = seed;
random_number_sequence_x(1) = random_number_x;

for i = 2:1:number_of_samples
    random_number_x = sawtooth(15*random_number_x*pi)/2+0.5;
    random_number_sequence_x(i) = random_number_x;
end

%random numbers
figure(1);
plot(random_number_sequence_x,'.');
title('Random numbers generated');

% 2x
figure(2);
random_number_sequence_in_1 = zeros(1,number_of_samples);
cdf_in_1 = zeros(1,number_of_samples);
for i = 1:1:number_of_samples
    random_number_sequence_in_1(i) = sqrt( random_number_sequence_x(i));
end

for i=1:1:number_of_samples

    cdf_in_1(i) = sum(random_number_sequence_in_1 < x(i))/number_of_samples;

end

subplot(2,2,1);
plot(x,2.*x);
title('Propability density function');
subplot(2,2,2);
plot(x,x.*x);
title('Cumulative distribution function');
subplot(2,2,3);
plot(x,random_number_sequence_in_1,'.');
title('Numbers generated by inverse method');
subplot(2,2,4);
stairs(x,cdf_in_1);
title('CDF of generated numbers');


% exponential
figure(3);

lambda = 1;
x = linspace(0,5,number_of_samples);

random_number_sequence_in_2 = zeros(1,number_of_samples);
cdf_in_2 = zeros(1,number_of_samples);
for i = 1:1:number_of_samples
    random_number_sequence_in_2(i) = -log(1-random_number_sequence_x(i))/lambda;
end

for i=1:1:number_of_samples

    cdf_in_2(i) = sum(random_number_sequence_in_2 < x(i))/number_of_samples;

end

subplot(2,2,1);
plot(x,lambda.*exp(-lambda.*x));
title('Propability density function');
subplot(2,2,2);
plot(x,1-exp(-lambda*x));
title('Cumulative distribution function');
subplot(2,2,3);
plot(x,random_number_sequence_in_2,'.');
title('Numbers generated by inverse method');
subplot(2,2,4);
stairs(x,cdf_in_2);
title('CDF of generated numbers');

% logistic
figure(4);

x = linspace(-10,10,number_of_samples);

random_number_sequence_in_3 = zeros(1,number_of_samples);
cdf_in_3 = zeros(1,number_of_samples);
for i = 1:1:number_of_samples
    random_number_sequence_in_3(i) = -log(1./random_number_sequence_x(i)-1);
end

for i=1:1:number_of_samples

    cdf_in_3(i) = sum(random_number_sequence_in_3 < x(i))/number_of_samples;

end

subplot(2,2,1);
plot(x,exp(-x)./((1+exp(-x)).*(1+exp(-x))));
title('Propability density function');
subplot(2,2,2);
plot(x,1./(1+exp(-x)));
title('Cumulative distribution function');
subplot(2,2,3);
plot(x,random_number_sequence_in_3,'.');
title('Numbers generated by inverse method');
subplot(2,2,4);
plot(x,cdf_in_3);
title('CDF of generated numbers');



% triangle
figure(5);

x = linspace(-2,2,number_of_samples);

random_number_sequence_in_4 = zeros(1,number_of_samples);
cdf_in_4 = zeros(1,number_of_samples);
cdf_in_4_ = zeros(1,number_of_samples);
pdf_in_4 = zeros(1,number_of_samples);
for i = 1:1:number_of_samples
    if(x(i) >= 0)
        pdf_in_4(i) = -x(i)/4+0.5;
        cdf_in_4_(i) = -x(i)*x(i)/8+x(i)/2+0.5;
    else
        pdf_in_4(i) = x(i)/4+0.5;
        cdf_in_4_(i) = x(i)*x(i)/8+x(i)/2+0.5;
    end
end

for i = 1:1:number_of_samples
    if(random_number_sequence_x(i) <= 0.5)
        random_number_sequence_in_4(i) = 2*sqrt(2*random_number_sequence_x(i))-2;
    else
        random_number_sequence_in_4(i) = -2*sqrt(2)*sqrt(1-random_number_sequence_x(i))+2;
    end
    
end

for i=1:1:number_of_samples

    cdf_in_4(i) = sum(random_number_sequence_in_4 < x(i))/number_of_samples;

end

subplot(2,2,1);
plot(x,pdf_in_4);
title('Propability density function');
subplot(2,2,2);
plot(x,cdf_in_4_);
title('Cumulative distribution function');
subplot(2,2,3);
plot(x,random_number_sequence_in_4,'.');
title('Numbers generated by inverse method');
subplot(2,2,4);
plot(x,cdf_in_4);
title('CDF of generated numbers');


